// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/inference/v2/inference.proto

package inferencev2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferRequest) Reset() {
	*x = InferRequest{}
	mi := &file_proto_inference_v2_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferRequest) ProtoMessage() {}

func (x *InferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_v2_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferRequest.ProtoReflect.Descriptor instead.
func (*InferRequest) Descriptor() ([]byte, []int) {
	return file_proto_inference_v2_inference_proto_rawDescGZIP(), []int{0}
}

func (x *InferRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InferRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *InferRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *InferRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type InferChunk struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Text            string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`                                               // The generated token(s)
	IsFinal         bool                   `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`                         // True on generation end
	GeneratedTokens int64                  `protobuf:"varint,4,opt,name=generated_tokens,json=generatedTokens,proto3" json:"generated_tokens,omitempty"` // Included in final chunk
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InferChunk) Reset() {
	*x = InferChunk{}
	mi := &file_proto_inference_v2_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferChunk) ProtoMessage() {}

func (x *InferChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_v2_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferChunk.ProtoReflect.Descriptor instead.
func (*InferChunk) Descriptor() ([]byte, []int) {
	return file_proto_inference_v2_inference_proto_rawDescGZIP(), []int{1}
}

func (x *InferChunk) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InferChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *InferChunk) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *InferChunk) GetGeneratedTokens() int64 {
	if x != nil {
		return x.GeneratedTokens
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_inference_v2_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_v2_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_inference_v2_inference_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_inference_v2_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_v2_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_inference_v2_inference_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_inference_v2_inference_proto protoreflect.FileDescriptor

const file_proto_inference_v2_inference_proto_rawDesc = "" +
	"\n" +
	"\"proto/inference/v2/inference.proto\x12\finference.v2\"\xe3\x01\n" +
	"\fInferRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12D\n" +
	"\bmetadata\x18\x04 \x03(\v2(.inference.v2.InferRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x01\n" +
	"\n" +
	"InferChunk\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal\x12)\n" +
	"\x10generated_tokens\x18\x04 \x01(\x03R\x0fgeneratedTokens\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xa3\x01\n" +
	"\x10InferenceService\x12E\n" +
	"\vInferStream\x12\x1a.inference.v2.InferRequest\x1a\x18.inference.v2.InferChunk0\x01\x12H\n" +
	"\vHealthCheck\x12\x1b.inference.v2.HealthRequest\x1a\x1c.inference.v2.HealthResponseBJZHgithub.com/powoftech/ai-inference-gateway/proto/inference/v2;inferencev2b\x06proto3"

var (
	file_proto_inference_v2_inference_proto_rawDescOnce sync.Once
	file_proto_inference_v2_inference_proto_rawDescData []byte
)

func file_proto_inference_v2_inference_proto_rawDescGZIP() []byte {
	file_proto_inference_v2_inference_proto_rawDescOnce.Do(func() {
		file_proto_inference_v2_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inference_v2_inference_proto_rawDesc), len(file_proto_inference_v2_inference_proto_rawDesc)))
	})
	return file_proto_inference_v2_inference_proto_rawDescData
}

var file_proto_inference_v2_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_inference_v2_inference_proto_goTypes = []any{
	(*InferRequest)(nil),   // 0: inference.v2.InferRequest
	(*InferChunk)(nil),     // 1: inference.v2.InferChunk
	(*HealthRequest)(nil),  // 2: inference.v2.HealthRequest
	(*HealthResponse)(nil), // 3: inference.v2.HealthResponse
	nil,                    // 4: inference.v2.InferRequest.MetadataEntry
}
var file_proto_inference_v2_inference_proto_depIdxs = []int32{
	4, // 0: inference.v2.InferRequest.metadata:type_name -> inference.v2.InferRequest.MetadataEntry
	0, // 1: inference.v2.InferenceService.InferStream:input_type -> inference.v2.InferRequest
	2, // 2: inference.v2.InferenceService.HealthCheck:input_type -> inference.v2.HealthRequest
	1, // 3: inference.v2.InferenceService.InferStream:output_type -> inference.v2.InferChunk
	3, // 4: inference.v2.InferenceService.HealthCheck:output_type -> inference.v2.HealthResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_inference_v2_inference_proto_init() }
func file_proto_inference_v2_inference_proto_init() {
	if File_proto_inference_v2_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inference_v2_inference_proto_rawDesc), len(file_proto_inference_v2_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inference_v2_inference_proto_goTypes,
		DependencyIndexes: file_proto_inference_v2_inference_proto_depIdxs,
		MessageInfos:      file_proto_inference_v2_inference_proto_msgTypes,
	}.Build()
	File_proto_inference_v2_inference_proto = out.File
	file_proto_inference_v2_inference_proto_goTypes = nil
	file_proto_inference_v2_inference_proto_depIdxs = nil
}
