name: ai-inference-gateway
services:
  redis-master:
    image: bitnami/redis:latest
    environment:
      REDIS_REPLICATION_MODE: master
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping || exit 1" ]
    restart: unless-stopped

  redis-replica:
    image: bitnami/redis:latest
    environment:
      REDIS_REPLICATION_MODE: slave
      REDIS_MASTER_HOST: redis-master
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping || exit 1" ]
    depends_on:
      redis-master:
        condition: service_healthy
    restart: unless-stopped

  redis-sentinel:
    image: bitnami/redis-sentinel:latest
    environment:
      REDIS_MASTER_HOST: redis-master
      REDIS_MASTER_SET: mymaster
      REDIS_SENTINEL_QUORUM: 1
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -p 26379 ping || exit 1" ]
    depends_on:
      redis-master:
        condition: service_healthy
      redis-replica:
        condition: service_healthy
    restart: unless-stopped

  mockbackend:
    build:
      context: .
      dockerfile: Dockerfile.mockbackend
    depends_on:
      redis-sentinel:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8080:8080"
    environment:
      # Inject Docker DNS names instead of localhost
      BACKEND_ADDRS: ai-inference-gateway-mockbackend-1:9091,ai-inference-gateway-mockbackend-2:9091,ai-inference-gateway-mockbackend-3:9091
      REDIS_SENTINEL_ADDR: redis-sentinel:26379
    depends_on:
      mockbackend:
        condition: service_started
      redis-sentinel:
        condition: service_healthy
    restart: unless-stopped
