# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x0cinference.v1\"p\n\x0fGenerateRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\'\n\x08messages\x18\x03 \x03(\x0b\x32\x15.inference.v1.Message\x12\x11\n\ttenant_id\x18\x04 \x01(\t\"(\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x80\x01\n\x10GenerateResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x13\n\x0bis_finished\x18\x03 \x01(\x08\x12\x18\n\x10tokens_generated\x18\x04 \x01(\x05\x12\x1a\n\x12processing_time_ms\x18\x05 \x01(\x05\x32\x63\n\x0cModelService\x12S\n\x0eGenerateStream\x12\x1d.inference.v1.GenerateRequest\x1a\x1e.inference.v1.GenerateResponse\"\x00\x30\x01\x42QZOgithub.com/powoftech/ai-inference-gateway/internal/gen/inference/v1;inferencev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZOgithub.com/powoftech/ai-inference-gateway/internal/gen/inference/v1;inferencev1'
  _globals['_GENERATEREQUEST']._serialized_start=33
  _globals['_GENERATEREQUEST']._serialized_end=145
  _globals['_MESSAGE']._serialized_start=147
  _globals['_MESSAGE']._serialized_end=187
  _globals['_GENERATERESPONSE']._serialized_start=190
  _globals['_GENERATERESPONSE']._serialized_end=318
  _globals['_MODELSERVICE']._serialized_start=320
  _globals['_MODELSERVICE']._serialized_end=419
# @@protoc_insertion_point(module_scope)
