import os
import sys
import time
from concurrent import futures
from collections.abc import Generator

import grpc

# These will be generated by grpcio-tools in your setup step
import inference_pb2
import inference_pb2_grpc


class ModelService(inference_pb2_grpc.ModelServiceServicer):
    def GenerateStream(
        self,
        request,
        context,
    ) -> Generator[inference_pb2.GenerateResponse, None, None]:
        """
        Simulates an LLM backend generating tokens via server streaming.
        """
        # 1. Simulate TTFT (Time To First Token) - GPU loading into VRAM
        time.sleep(0.100)  # 100ms sleep

        mock_text = "Hello, this is a mock response from the GreenNode AI cluster."
        words = mock_text.split(" ")

        start_time = time.time()
        tokens_generated = 0

        for i, word in enumerate(words):
            # 2. Simulate token generation time
            time.sleep(0.020)  # 20ms per token

            is_finished = i == len(words) - 1
            # Add space back to words unless it's the last token
            token_str = word + ("" if is_finished else " ")
            tokens_generated += 1

            processing_time_ms = int((time.time() - start_time) * 1000)

            # 3. Yield the response chunk back over the gRPC stream
            yield inference_pb2.GenerateResponse(
                request_id=request.request_id,
                token=token_str,
                is_finished=is_finished,
                tokens_generated=tokens_generated,
                processing_time_ms=processing_time_ms,
            )


def serve():
    # Configure thread pool for handling concurrent gRPC connections
    server: grpc.Server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    inference_pb2_grpc.add_ModelServiceServicer_to_server(ModelService(), server)

    # 12-Factor App: Resolve port via CLI argument, Environment Variable, or Default
    port = "50051"
    if len(sys.argv) > 1:
        port = sys.argv[1]
    elif os.environ.get("PORT"):
        port = os.environ.get("PORT")

    address = f"[::]:{port}"
    server.add_insecure_port(address)
    print(f"Mock Python Backend listening securely on {address}...")

    server.start()
    server.wait_for_termination()


if __name__ == "__main__":
    serve()
