// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/inference/v1/inference.proto

package inferencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Model     string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Messages  []*Message             `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	// Metadata for tracing, routing, and quota enforcement
	TenantId      string `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_proto_inference_v1_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_v1_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_proto_inference_v1_inference_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GenerateRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GenerateRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_inference_v1_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_v1_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_inference_v1_inference_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GenerateResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RequestId  string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Token      string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	IsFinished bool                   `protobuf:"varint,3,opt,name=is_finished,json=isFinished,proto3" json:"is_finished,omitempty"`
	// Metrics reported back to the gateway for EWMA routing logic
	TokensGenerated  int32 `protobuf:"varint,4,opt,name=tokens_generated,json=tokensGenerated,proto3" json:"tokens_generated,omitempty"`
	ProcessingTimeMs int32 `protobuf:"varint,5,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_proto_inference_v1_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_v1_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_proto_inference_v1_inference_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GenerateResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GenerateResponse) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

func (x *GenerateResponse) GetTokensGenerated() int32 {
	if x != nil {
		return x.TokensGenerated
	}
	return 0
}

func (x *GenerateResponse) GetProcessingTimeMs() int32 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

var File_proto_inference_v1_inference_proto protoreflect.FileDescriptor

const file_proto_inference_v1_inference_proto_rawDesc = "" +
	"\n" +
	"\"proto/inference/v1/inference.proto\x12\finference.v1\"\x96\x01\n" +
	"\x0fGenerateRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x121\n" +
	"\bmessages\x18\x03 \x03(\v2\x15.inference.v1.MessageR\bmessages\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xc1\x01\n" +
	"\x10GenerateResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1f\n" +
	"\vis_finished\x18\x03 \x01(\bR\n" +
	"isFinished\x12)\n" +
	"\x10tokens_generated\x18\x04 \x01(\x05R\x0ftokensGenerated\x12,\n" +
	"\x12processing_time_ms\x18\x05 \x01(\x05R\x10processingTimeMs2c\n" +
	"\fModelService\x12S\n" +
	"\x0eGenerateStream\x12\x1d.inference.v1.GenerateRequest\x1a\x1e.inference.v1.GenerateResponse\"\x000\x01BQZOgithub.com/powoftech/ai-inference-gateway/internal/gen/inference/v1;inferencev1b\x06proto3"

var (
	file_proto_inference_v1_inference_proto_rawDescOnce sync.Once
	file_proto_inference_v1_inference_proto_rawDescData []byte
)

func file_proto_inference_v1_inference_proto_rawDescGZIP() []byte {
	file_proto_inference_v1_inference_proto_rawDescOnce.Do(func() {
		file_proto_inference_v1_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inference_v1_inference_proto_rawDesc), len(file_proto_inference_v1_inference_proto_rawDesc)))
	})
	return file_proto_inference_v1_inference_proto_rawDescData
}

var file_proto_inference_v1_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_inference_v1_inference_proto_goTypes = []any{
	(*GenerateRequest)(nil),  // 0: inference.v1.GenerateRequest
	(*Message)(nil),          // 1: inference.v1.Message
	(*GenerateResponse)(nil), // 2: inference.v1.GenerateResponse
}
var file_proto_inference_v1_inference_proto_depIdxs = []int32{
	1, // 0: inference.v1.GenerateRequest.messages:type_name -> inference.v1.Message
	0, // 1: inference.v1.ModelService.GenerateStream:input_type -> inference.v1.GenerateRequest
	2, // 2: inference.v1.ModelService.GenerateStream:output_type -> inference.v1.GenerateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_inference_v1_inference_proto_init() }
func file_proto_inference_v1_inference_proto_init() {
	if File_proto_inference_v1_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inference_v1_inference_proto_rawDesc), len(file_proto_inference_v1_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inference_v1_inference_proto_goTypes,
		DependencyIndexes: file_proto_inference_v1_inference_proto_depIdxs,
		MessageInfos:      file_proto_inference_v1_inference_proto_msgTypes,
	}.Build()
	File_proto_inference_v1_inference_proto = out.File
	file_proto_inference_v1_inference_proto_goTypes = nil
	file_proto_inference_v1_inference_proto_depIdxs = nil
}
